# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bioeecoinsmain.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BioEECoinsMain(object):
    def setupUi(self, BioEECoinsMain):
        BioEECoinsMain.setObjectName("BioEECoinsMain")
        BioEECoinsMain.resize(1280, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(BioEECoinsMain.sizePolicy().hasHeightForWidth())
        BioEECoinsMain.setSizePolicy(sizePolicy)
        BioEECoinsMain.setMinimumSize(QtCore.QSize(1280, 720))
        BioEECoinsMain.setMaximumSize(QtCore.QSize(1280, 720))
        self.centralWidget = QtWidgets.QWidget(BioEECoinsMain)
        self.centralWidget.setMaximumSize(QtCore.QSize(1280, 720))
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setContentsMargins(20, 20, 20, 20)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralWidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 132, 1359))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_6 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_6.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_6.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_52 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_52.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_52.setSpacing(6)
        self.horizontalLayout_52.setObjectName("horizontalLayout_52")
        self.led_1 = QtWidgets.QLabel(self.widget_6)
        self.led_1.setMaximumSize(QtCore.QSize(16, 16))
        self.led_1.setText("")
        self.led_1.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_1.setObjectName("led_1")
        self.horizontalLayout_52.addWidget(self.led_1)
        self.channel_sel_1 = QtWidgets.QPushButton(self.widget_6)
        self.channel_sel_1.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_1.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_1.setFont(font)
        self.channel_sel_1.setObjectName("channel_sel_1")
        self.horizontalLayout_52.addWidget(self.channel_sel_1)
        self.verticalLayout.addWidget(self.widget_6)
        self.widget_7 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_7.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_7.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_53 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_53.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_53.setSpacing(6)
        self.horizontalLayout_53.setObjectName("horizontalLayout_53")
        self.led_2 = QtWidgets.QLabel(self.widget_7)
        self.led_2.setMaximumSize(QtCore.QSize(16, 16))
        self.led_2.setText("")
        self.led_2.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_2.setObjectName("led_2")
        self.horizontalLayout_53.addWidget(self.led_2)
        self.channel_sel_2 = QtWidgets.QPushButton(self.widget_7)
        self.channel_sel_2.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_2.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_2.setFont(font)
        self.channel_sel_2.setObjectName("channel_sel_2")
        self.horizontalLayout_53.addWidget(self.channel_sel_2)
        self.verticalLayout.addWidget(self.widget_7)
        self.widget_8 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_8.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_8.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_54 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_54.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_54.setSpacing(6)
        self.horizontalLayout_54.setObjectName("horizontalLayout_54")
        self.led_3 = QtWidgets.QLabel(self.widget_8)
        self.led_3.setMaximumSize(QtCore.QSize(16, 16))
        self.led_3.setText("")
        self.led_3.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_3.setObjectName("led_3")
        self.horizontalLayout_54.addWidget(self.led_3)
        self.channel_sel_3 = QtWidgets.QPushButton(self.widget_8)
        self.channel_sel_3.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_3.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_3.setFont(font)
        self.channel_sel_3.setObjectName("channel_sel_3")
        self.horizontalLayout_54.addWidget(self.channel_sel_3)
        self.verticalLayout.addWidget(self.widget_8)
        self.widget_9 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_9.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_9.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_55 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_55.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_55.setSpacing(6)
        self.horizontalLayout_55.setObjectName("horizontalLayout_55")
        self.led_4 = QtWidgets.QLabel(self.widget_9)
        self.led_4.setMaximumSize(QtCore.QSize(16, 16))
        self.led_4.setText("")
        self.led_4.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_4.setObjectName("led_4")
        self.horizontalLayout_55.addWidget(self.led_4)
        self.channel_sel_4 = QtWidgets.QPushButton(self.widget_9)
        self.channel_sel_4.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_4.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_4.setFont(font)
        self.channel_sel_4.setObjectName("channel_sel_4")
        self.horizontalLayout_55.addWidget(self.channel_sel_4)
        self.verticalLayout.addWidget(self.widget_9)
        self.widget_10 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_10.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_10.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_56 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_56.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_56.setSpacing(6)
        self.horizontalLayout_56.setObjectName("horizontalLayout_56")
        self.led_5 = QtWidgets.QLabel(self.widget_10)
        self.led_5.setMaximumSize(QtCore.QSize(16, 16))
        self.led_5.setText("")
        self.led_5.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_5.setObjectName("led_5")
        self.horizontalLayout_56.addWidget(self.led_5)
        self.channel_sel_5 = QtWidgets.QPushButton(self.widget_10)
        self.channel_sel_5.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_5.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_5.setFont(font)
        self.channel_sel_5.setObjectName("channel_sel_5")
        self.horizontalLayout_56.addWidget(self.channel_sel_5)
        self.verticalLayout.addWidget(self.widget_10)
        self.widget_11 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_11.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_11.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_57 = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout_57.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_57.setSpacing(6)
        self.horizontalLayout_57.setObjectName("horizontalLayout_57")
        self.led_6 = QtWidgets.QLabel(self.widget_11)
        self.led_6.setMaximumSize(QtCore.QSize(16, 16))
        self.led_6.setText("")
        self.led_6.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_6.setObjectName("led_6")
        self.horizontalLayout_57.addWidget(self.led_6)
        self.channel_sel_6 = QtWidgets.QPushButton(self.widget_11)
        self.channel_sel_6.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_6.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_6.setFont(font)
        self.channel_sel_6.setObjectName("channel_sel_6")
        self.horizontalLayout_57.addWidget(self.channel_sel_6)
        self.verticalLayout.addWidget(self.widget_11)
        self.widget_12 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_12.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_12.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_12.setObjectName("widget_12")
        self.horizontalLayout_58 = QtWidgets.QHBoxLayout(self.widget_12)
        self.horizontalLayout_58.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_58.setSpacing(6)
        self.horizontalLayout_58.setObjectName("horizontalLayout_58")
        self.led_7 = QtWidgets.QLabel(self.widget_12)
        self.led_7.setMaximumSize(QtCore.QSize(16, 16))
        self.led_7.setText("")
        self.led_7.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_7.setObjectName("led_7")
        self.horizontalLayout_58.addWidget(self.led_7)
        self.channel_sel_7 = QtWidgets.QPushButton(self.widget_12)
        self.channel_sel_7.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_7.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_7.setFont(font)
        self.channel_sel_7.setObjectName("channel_sel_7")
        self.horizontalLayout_58.addWidget(self.channel_sel_7)
        self.verticalLayout.addWidget(self.widget_12)
        self.widget_13 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_13.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_13.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_13.setObjectName("widget_13")
        self.horizontalLayout_59 = QtWidgets.QHBoxLayout(self.widget_13)
        self.horizontalLayout_59.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_59.setSpacing(6)
        self.horizontalLayout_59.setObjectName("horizontalLayout_59")
        self.led_8 = QtWidgets.QLabel(self.widget_13)
        self.led_8.setMaximumSize(QtCore.QSize(16, 16))
        self.led_8.setText("")
        self.led_8.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_8.setObjectName("led_8")
        self.horizontalLayout_59.addWidget(self.led_8)
        self.channel_sel_8 = QtWidgets.QPushButton(self.widget_13)
        self.channel_sel_8.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_8.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_8.setFont(font)
        self.channel_sel_8.setObjectName("channel_sel_8")
        self.horizontalLayout_59.addWidget(self.channel_sel_8)
        self.verticalLayout.addWidget(self.widget_13)
        self.widget_14 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_14.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_14.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_14.setObjectName("widget_14")
        self.horizontalLayout_60 = QtWidgets.QHBoxLayout(self.widget_14)
        self.horizontalLayout_60.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_60.setSpacing(6)
        self.horizontalLayout_60.setObjectName("horizontalLayout_60")
        self.led_9 = QtWidgets.QLabel(self.widget_14)
        self.led_9.setMaximumSize(QtCore.QSize(16, 16))
        self.led_9.setText("")
        self.led_9.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_9.setObjectName("led_9")
        self.horizontalLayout_60.addWidget(self.led_9)
        self.channel_sel_9 = QtWidgets.QPushButton(self.widget_14)
        self.channel_sel_9.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_9.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_9.setFont(font)
        self.channel_sel_9.setObjectName("channel_sel_9")
        self.horizontalLayout_60.addWidget(self.channel_sel_9)
        self.verticalLayout.addWidget(self.widget_14)
        self.widget_15 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_15.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_15.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_15.setObjectName("widget_15")
        self.horizontalLayout_61 = QtWidgets.QHBoxLayout(self.widget_15)
        self.horizontalLayout_61.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_61.setSpacing(6)
        self.horizontalLayout_61.setObjectName("horizontalLayout_61")
        self.led_10 = QtWidgets.QLabel(self.widget_15)
        self.led_10.setMaximumSize(QtCore.QSize(16, 16))
        self.led_10.setText("")
        self.led_10.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_10.setObjectName("led_10")
        self.horizontalLayout_61.addWidget(self.led_10)
        self.channel_sel_10 = QtWidgets.QPushButton(self.widget_15)
        self.channel_sel_10.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_10.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_10.setFont(font)
        self.channel_sel_10.setObjectName("channel_sel_10")
        self.horizontalLayout_61.addWidget(self.channel_sel_10)
        self.verticalLayout.addWidget(self.widget_15)
        self.widget_16 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_16.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_16.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_16.setObjectName("widget_16")
        self.horizontalLayout_62 = QtWidgets.QHBoxLayout(self.widget_16)
        self.horizontalLayout_62.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_62.setSpacing(6)
        self.horizontalLayout_62.setObjectName("horizontalLayout_62")
        self.led_11 = QtWidgets.QLabel(self.widget_16)
        self.led_11.setMaximumSize(QtCore.QSize(16, 16))
        self.led_11.setText("")
        self.led_11.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_11.setObjectName("led_11")
        self.horizontalLayout_62.addWidget(self.led_11)
        self.channel_sel_11 = QtWidgets.QPushButton(self.widget_16)
        self.channel_sel_11.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_11.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_11.setFont(font)
        self.channel_sel_11.setObjectName("channel_sel_11")
        self.horizontalLayout_62.addWidget(self.channel_sel_11)
        self.verticalLayout.addWidget(self.widget_16)
        self.widget_17 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_17.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_17.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_17.setObjectName("widget_17")
        self.horizontalLayout_63 = QtWidgets.QHBoxLayout(self.widget_17)
        self.horizontalLayout_63.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_63.setSpacing(6)
        self.horizontalLayout_63.setObjectName("horizontalLayout_63")
        self.led_12 = QtWidgets.QLabel(self.widget_17)
        self.led_12.setMaximumSize(QtCore.QSize(16, 16))
        self.led_12.setText("")
        self.led_12.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_12.setObjectName("led_12")
        self.horizontalLayout_63.addWidget(self.led_12)
        self.channel_sel_12 = QtWidgets.QPushButton(self.widget_17)
        self.channel_sel_12.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_12.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_12.setFont(font)
        self.channel_sel_12.setObjectName("channel_sel_12")
        self.horizontalLayout_63.addWidget(self.channel_sel_12)
        self.verticalLayout.addWidget(self.widget_17)
        self.widget_18 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_18.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_18.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_18.setObjectName("widget_18")
        self.horizontalLayout_64 = QtWidgets.QHBoxLayout(self.widget_18)
        self.horizontalLayout_64.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_64.setSpacing(6)
        self.horizontalLayout_64.setObjectName("horizontalLayout_64")
        self.led_13 = QtWidgets.QLabel(self.widget_18)
        self.led_13.setMaximumSize(QtCore.QSize(16, 16))
        self.led_13.setText("")
        self.led_13.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_13.setObjectName("led_13")
        self.horizontalLayout_64.addWidget(self.led_13)
        self.channel_sel_13 = QtWidgets.QPushButton(self.widget_18)
        self.channel_sel_13.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_13.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_13.setFont(font)
        self.channel_sel_13.setObjectName("channel_sel_13")
        self.horizontalLayout_64.addWidget(self.channel_sel_13)
        self.verticalLayout.addWidget(self.widget_18)
        self.widget_19 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_19.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_19.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_19.setObjectName("widget_19")
        self.horizontalLayout_65 = QtWidgets.QHBoxLayout(self.widget_19)
        self.horizontalLayout_65.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_65.setSpacing(6)
        self.horizontalLayout_65.setObjectName("horizontalLayout_65")
        self.led_14 = QtWidgets.QLabel(self.widget_19)
        self.led_14.setMaximumSize(QtCore.QSize(16, 16))
        self.led_14.setText("")
        self.led_14.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_14.setObjectName("led_14")
        self.horizontalLayout_65.addWidget(self.led_14)
        self.channel_sel_14 = QtWidgets.QPushButton(self.widget_19)
        self.channel_sel_14.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_14.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_14.setFont(font)
        self.channel_sel_14.setObjectName("channel_sel_14")
        self.horizontalLayout_65.addWidget(self.channel_sel_14)
        self.verticalLayout.addWidget(self.widget_19)
        self.widget_20 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_20.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_20.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_20.setObjectName("widget_20")
        self.horizontalLayout_66 = QtWidgets.QHBoxLayout(self.widget_20)
        self.horizontalLayout_66.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_66.setSpacing(6)
        self.horizontalLayout_66.setObjectName("horizontalLayout_66")
        self.led_15 = QtWidgets.QLabel(self.widget_20)
        self.led_15.setMaximumSize(QtCore.QSize(16, 16))
        self.led_15.setText("")
        self.led_15.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_15.setObjectName("led_15")
        self.horizontalLayout_66.addWidget(self.led_15)
        self.channel_sel_15 = QtWidgets.QPushButton(self.widget_20)
        self.channel_sel_15.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_15.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_15.setFont(font)
        self.channel_sel_15.setObjectName("channel_sel_15")
        self.horizontalLayout_66.addWidget(self.channel_sel_15)
        self.verticalLayout.addWidget(self.widget_20)
        self.widget_21 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_21.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_21.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_21.setObjectName("widget_21")
        self.horizontalLayout_67 = QtWidgets.QHBoxLayout(self.widget_21)
        self.horizontalLayout_67.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_67.setSpacing(6)
        self.horizontalLayout_67.setObjectName("horizontalLayout_67")
        self.led_16 = QtWidgets.QLabel(self.widget_21)
        self.led_16.setMaximumSize(QtCore.QSize(16, 16))
        self.led_16.setText("")
        self.led_16.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_16.setObjectName("led_16")
        self.horizontalLayout_67.addWidget(self.led_16)
        self.channel_sel_16 = QtWidgets.QPushButton(self.widget_21)
        self.channel_sel_16.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_16.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_16.setFont(font)
        self.channel_sel_16.setObjectName("channel_sel_16")
        self.horizontalLayout_67.addWidget(self.channel_sel_16)
        self.verticalLayout.addWidget(self.widget_21)
        self.widget_22 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_22.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_22.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_22.setObjectName("widget_22")
        self.horizontalLayout_68 = QtWidgets.QHBoxLayout(self.widget_22)
        self.horizontalLayout_68.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_68.setSpacing(6)
        self.horizontalLayout_68.setObjectName("horizontalLayout_68")
        self.led_17 = QtWidgets.QLabel(self.widget_22)
        self.led_17.setMaximumSize(QtCore.QSize(16, 16))
        self.led_17.setText("")
        self.led_17.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_17.setObjectName("led_17")
        self.horizontalLayout_68.addWidget(self.led_17)
        self.channel_sel_17 = QtWidgets.QPushButton(self.widget_22)
        self.channel_sel_17.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_17.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_17.setFont(font)
        self.channel_sel_17.setObjectName("channel_sel_17")
        self.horizontalLayout_68.addWidget(self.channel_sel_17)
        self.verticalLayout.addWidget(self.widget_22)
        self.widget_23 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_23.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_23.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_23.setObjectName("widget_23")
        self.horizontalLayout_69 = QtWidgets.QHBoxLayout(self.widget_23)
        self.horizontalLayout_69.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_69.setSpacing(6)
        self.horizontalLayout_69.setObjectName("horizontalLayout_69")
        self.led_18 = QtWidgets.QLabel(self.widget_23)
        self.led_18.setMaximumSize(QtCore.QSize(16, 16))
        self.led_18.setText("")
        self.led_18.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_18.setObjectName("led_18")
        self.horizontalLayout_69.addWidget(self.led_18)
        self.channel_sel_18 = QtWidgets.QPushButton(self.widget_23)
        self.channel_sel_18.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_18.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_18.setFont(font)
        self.channel_sel_18.setObjectName("channel_sel_18")
        self.horizontalLayout_69.addWidget(self.channel_sel_18)
        self.verticalLayout.addWidget(self.widget_23)
        self.widget_24 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_24.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_24.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_24.setObjectName("widget_24")
        self.horizontalLayout_70 = QtWidgets.QHBoxLayout(self.widget_24)
        self.horizontalLayout_70.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_70.setSpacing(6)
        self.horizontalLayout_70.setObjectName("horizontalLayout_70")
        self.led_19 = QtWidgets.QLabel(self.widget_24)
        self.led_19.setMaximumSize(QtCore.QSize(16, 16))
        self.led_19.setText("")
        self.led_19.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_19.setObjectName("led_19")
        self.horizontalLayout_70.addWidget(self.led_19)
        self.channel_sel_19 = QtWidgets.QPushButton(self.widget_24)
        self.channel_sel_19.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_19.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_19.setFont(font)
        self.channel_sel_19.setObjectName("channel_sel_19")
        self.horizontalLayout_70.addWidget(self.channel_sel_19)
        self.verticalLayout.addWidget(self.widget_24)
        self.widget_25 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_25.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_25.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_25.setObjectName("widget_25")
        self.horizontalLayout_71 = QtWidgets.QHBoxLayout(self.widget_25)
        self.horizontalLayout_71.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_71.setSpacing(6)
        self.horizontalLayout_71.setObjectName("horizontalLayout_71")
        self.led_20 = QtWidgets.QLabel(self.widget_25)
        self.led_20.setMaximumSize(QtCore.QSize(16, 16))
        self.led_20.setText("")
        self.led_20.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_20.setObjectName("led_20")
        self.horizontalLayout_71.addWidget(self.led_20)
        self.channel_sel_20 = QtWidgets.QPushButton(self.widget_25)
        self.channel_sel_20.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_20.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_20.setFont(font)
        self.channel_sel_20.setObjectName("channel_sel_20")
        self.horizontalLayout_71.addWidget(self.channel_sel_20)
        self.verticalLayout.addWidget(self.widget_25)
        self.widget_26 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_26.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_26.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_26.setObjectName("widget_26")
        self.horizontalLayout_72 = QtWidgets.QHBoxLayout(self.widget_26)
        self.horizontalLayout_72.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_72.setSpacing(6)
        self.horizontalLayout_72.setObjectName("horizontalLayout_72")
        self.led_21 = QtWidgets.QLabel(self.widget_26)
        self.led_21.setMaximumSize(QtCore.QSize(16, 16))
        self.led_21.setText("")
        self.led_21.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_21.setObjectName("led_21")
        self.horizontalLayout_72.addWidget(self.led_21)
        self.channel_sel_21 = QtWidgets.QPushButton(self.widget_26)
        self.channel_sel_21.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_21.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_21.setFont(font)
        self.channel_sel_21.setObjectName("channel_sel_21")
        self.horizontalLayout_72.addWidget(self.channel_sel_21)
        self.verticalLayout.addWidget(self.widget_26)
        self.widget_27 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_27.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_27.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_27.setObjectName("widget_27")
        self.horizontalLayout_73 = QtWidgets.QHBoxLayout(self.widget_27)
        self.horizontalLayout_73.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_73.setSpacing(6)
        self.horizontalLayout_73.setObjectName("horizontalLayout_73")
        self.led_22 = QtWidgets.QLabel(self.widget_27)
        self.led_22.setMaximumSize(QtCore.QSize(16, 16))
        self.led_22.setText("")
        self.led_22.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_22.setObjectName("led_22")
        self.horizontalLayout_73.addWidget(self.led_22)
        self.channel_sel_22 = QtWidgets.QPushButton(self.widget_27)
        self.channel_sel_22.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_22.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_22.setFont(font)
        self.channel_sel_22.setObjectName("channel_sel_22")
        self.horizontalLayout_73.addWidget(self.channel_sel_22)
        self.verticalLayout.addWidget(self.widget_27)
        self.widget_28 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_28.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_28.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_28.setObjectName("widget_28")
        self.horizontalLayout_74 = QtWidgets.QHBoxLayout(self.widget_28)
        self.horizontalLayout_74.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_74.setSpacing(6)
        self.horizontalLayout_74.setObjectName("horizontalLayout_74")
        self.led_23 = QtWidgets.QLabel(self.widget_28)
        self.led_23.setMaximumSize(QtCore.QSize(16, 16))
        self.led_23.setText("")
        self.led_23.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_23.setObjectName("led_23")
        self.horizontalLayout_74.addWidget(self.led_23)
        self.channel_sel_23 = QtWidgets.QPushButton(self.widget_28)
        self.channel_sel_23.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_23.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_23.setFont(font)
        self.channel_sel_23.setObjectName("channel_sel_23")
        self.horizontalLayout_74.addWidget(self.channel_sel_23)
        self.verticalLayout.addWidget(self.widget_28)
        self.widget_29 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_29.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_29.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_29.setObjectName("widget_29")
        self.horizontalLayout_75 = QtWidgets.QHBoxLayout(self.widget_29)
        self.horizontalLayout_75.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_75.setSpacing(6)
        self.horizontalLayout_75.setObjectName("horizontalLayout_75")
        self.led_24 = QtWidgets.QLabel(self.widget_29)
        self.led_24.setMaximumSize(QtCore.QSize(16, 16))
        self.led_24.setText("")
        self.led_24.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_24.setObjectName("led_24")
        self.horizontalLayout_75.addWidget(self.led_24)
        self.channel_sel_24 = QtWidgets.QPushButton(self.widget_29)
        self.channel_sel_24.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_24.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_24.setFont(font)
        self.channel_sel_24.setObjectName("channel_sel_24")
        self.horizontalLayout_75.addWidget(self.channel_sel_24)
        self.verticalLayout.addWidget(self.widget_29)
        self.widget_30 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_30.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_30.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_30.setObjectName("widget_30")
        self.horizontalLayout_76 = QtWidgets.QHBoxLayout(self.widget_30)
        self.horizontalLayout_76.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_76.setSpacing(6)
        self.horizontalLayout_76.setObjectName("horizontalLayout_76")
        self.led_25 = QtWidgets.QLabel(self.widget_30)
        self.led_25.setMaximumSize(QtCore.QSize(16, 16))
        self.led_25.setText("")
        self.led_25.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_25.setObjectName("led_25")
        self.horizontalLayout_76.addWidget(self.led_25)
        self.channel_sel_25 = QtWidgets.QPushButton(self.widget_30)
        self.channel_sel_25.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_25.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_25.setFont(font)
        self.channel_sel_25.setObjectName("channel_sel_25")
        self.horizontalLayout_76.addWidget(self.channel_sel_25)
        self.verticalLayout.addWidget(self.widget_30)
        self.widget_31 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_31.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_31.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_31.setObjectName("widget_31")
        self.horizontalLayout_77 = QtWidgets.QHBoxLayout(self.widget_31)
        self.horizontalLayout_77.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_77.setSpacing(6)
        self.horizontalLayout_77.setObjectName("horizontalLayout_77")
        self.led_26 = QtWidgets.QLabel(self.widget_31)
        self.led_26.setMaximumSize(QtCore.QSize(16, 16))
        self.led_26.setText("")
        self.led_26.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_26.setObjectName("led_26")
        self.horizontalLayout_77.addWidget(self.led_26)
        self.channel_sel_26 = QtWidgets.QPushButton(self.widget_31)
        self.channel_sel_26.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_26.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_26.setFont(font)
        self.channel_sel_26.setObjectName("channel_sel_26")
        self.horizontalLayout_77.addWidget(self.channel_sel_26)
        self.verticalLayout.addWidget(self.widget_31)
        self.widget_32 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_32.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_32.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_32.setObjectName("widget_32")
        self.horizontalLayout_78 = QtWidgets.QHBoxLayout(self.widget_32)
        self.horizontalLayout_78.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_78.setSpacing(6)
        self.horizontalLayout_78.setObjectName("horizontalLayout_78")
        self.led_27 = QtWidgets.QLabel(self.widget_32)
        self.led_27.setMaximumSize(QtCore.QSize(16, 16))
        self.led_27.setText("")
        self.led_27.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_27.setObjectName("led_27")
        self.horizontalLayout_78.addWidget(self.led_27)
        self.channel_sel_27 = QtWidgets.QPushButton(self.widget_32)
        self.channel_sel_27.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_27.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_27.setFont(font)
        self.channel_sel_27.setObjectName("channel_sel_27")
        self.horizontalLayout_78.addWidget(self.channel_sel_27)
        self.verticalLayout.addWidget(self.widget_32)
        self.widget_33 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_33.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_33.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_33.setObjectName("widget_33")
        self.horizontalLayout_79 = QtWidgets.QHBoxLayout(self.widget_33)
        self.horizontalLayout_79.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_79.setSpacing(6)
        self.horizontalLayout_79.setObjectName("horizontalLayout_79")
        self.led_28 = QtWidgets.QLabel(self.widget_33)
        self.led_28.setMaximumSize(QtCore.QSize(16, 16))
        self.led_28.setText("")
        self.led_28.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_28.setObjectName("led_28")
        self.horizontalLayout_79.addWidget(self.led_28)
        self.channel_sel_28 = QtWidgets.QPushButton(self.widget_33)
        self.channel_sel_28.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_28.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_28.setFont(font)
        self.channel_sel_28.setObjectName("channel_sel_28")
        self.horizontalLayout_79.addWidget(self.channel_sel_28)
        self.verticalLayout.addWidget(self.widget_33)
        self.widget_34 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_34.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_34.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_34.setObjectName("widget_34")
        self.horizontalLayout_80 = QtWidgets.QHBoxLayout(self.widget_34)
        self.horizontalLayout_80.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_80.setSpacing(6)
        self.horizontalLayout_80.setObjectName("horizontalLayout_80")
        self.led_29 = QtWidgets.QLabel(self.widget_34)
        self.led_29.setMaximumSize(QtCore.QSize(16, 16))
        self.led_29.setText("")
        self.led_29.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_29.setObjectName("led_29")
        self.horizontalLayout_80.addWidget(self.led_29)
        self.channel_sel_29 = QtWidgets.QPushButton(self.widget_34)
        self.channel_sel_29.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_29.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_29.setFont(font)
        self.channel_sel_29.setObjectName("channel_sel_29")
        self.horizontalLayout_80.addWidget(self.channel_sel_29)
        self.verticalLayout.addWidget(self.widget_34)
        self.widget_35 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_35.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_35.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_35.setObjectName("widget_35")
        self.horizontalLayout_81 = QtWidgets.QHBoxLayout(self.widget_35)
        self.horizontalLayout_81.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_81.setSpacing(6)
        self.horizontalLayout_81.setObjectName("horizontalLayout_81")
        self.led_30 = QtWidgets.QLabel(self.widget_35)
        self.led_30.setMaximumSize(QtCore.QSize(16, 16))
        self.led_30.setText("")
        self.led_30.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_30.setObjectName("led_30")
        self.horizontalLayout_81.addWidget(self.led_30)
        self.channel_sel_30 = QtWidgets.QPushButton(self.widget_35)
        self.channel_sel_30.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_30.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_30.setFont(font)
        self.channel_sel_30.setObjectName("channel_sel_30")
        self.horizontalLayout_81.addWidget(self.channel_sel_30)
        self.verticalLayout.addWidget(self.widget_35)
        self.widget_36 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_36.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_36.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_36.setObjectName("widget_36")
        self.horizontalLayout_82 = QtWidgets.QHBoxLayout(self.widget_36)
        self.horizontalLayout_82.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_82.setSpacing(6)
        self.horizontalLayout_82.setObjectName("horizontalLayout_82")
        self.led_31 = QtWidgets.QLabel(self.widget_36)
        self.led_31.setMaximumSize(QtCore.QSize(16, 16))
        self.led_31.setText("")
        self.led_31.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_31.setObjectName("led_31")
        self.horizontalLayout_82.addWidget(self.led_31)
        self.channel_sel_31 = QtWidgets.QPushButton(self.widget_36)
        self.channel_sel_31.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_31.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_31.setFont(font)
        self.channel_sel_31.setObjectName("channel_sel_31")
        self.horizontalLayout_82.addWidget(self.channel_sel_31)
        self.verticalLayout.addWidget(self.widget_36)
        self.widget_37 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_37.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_37.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_37.setObjectName("widget_37")
        self.horizontalLayout_83 = QtWidgets.QHBoxLayout(self.widget_37)
        self.horizontalLayout_83.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_83.setSpacing(6)
        self.horizontalLayout_83.setObjectName("horizontalLayout_83")
        self.led_32 = QtWidgets.QLabel(self.widget_37)
        self.led_32.setMaximumSize(QtCore.QSize(16, 16))
        self.led_32.setText("")
        self.led_32.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_32.setObjectName("led_32")
        self.horizontalLayout_83.addWidget(self.led_32)
        self.channel_sel_32 = QtWidgets.QPushButton(self.widget_37)
        self.channel_sel_32.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_32.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_32.setFont(font)
        self.channel_sel_32.setObjectName("channel_sel_32")
        self.horizontalLayout_83.addWidget(self.channel_sel_32)
        self.verticalLayout.addWidget(self.widget_37)
        self.widget_38 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_38.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_38.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_38.setObjectName("widget_38")
        self.horizontalLayout_84 = QtWidgets.QHBoxLayout(self.widget_38)
        self.horizontalLayout_84.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_84.setSpacing(6)
        self.horizontalLayout_84.setObjectName("horizontalLayout_84")
        self.led_33 = QtWidgets.QLabel(self.widget_38)
        self.led_33.setMaximumSize(QtCore.QSize(16, 16))
        self.led_33.setText("")
        self.led_33.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_33.setObjectName("led_33")
        self.horizontalLayout_84.addWidget(self.led_33)
        self.channel_sel_33 = QtWidgets.QPushButton(self.widget_38)
        self.channel_sel_33.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_33.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_33.setFont(font)
        self.channel_sel_33.setObjectName("channel_sel_33")
        self.horizontalLayout_84.addWidget(self.channel_sel_33)
        self.verticalLayout.addWidget(self.widget_38)
        self.widget_39 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_39.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_39.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_39.setObjectName("widget_39")
        self.horizontalLayout_85 = QtWidgets.QHBoxLayout(self.widget_39)
        self.horizontalLayout_85.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_85.setSpacing(6)
        self.horizontalLayout_85.setObjectName("horizontalLayout_85")
        self.led_34 = QtWidgets.QLabel(self.widget_39)
        self.led_34.setMaximumSize(QtCore.QSize(16, 16))
        self.led_34.setText("")
        self.led_34.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_34.setObjectName("led_34")
        self.horizontalLayout_85.addWidget(self.led_34)
        self.channel_sel_34 = QtWidgets.QPushButton(self.widget_39)
        self.channel_sel_34.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_34.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_34.setFont(font)
        self.channel_sel_34.setObjectName("channel_sel_34")
        self.horizontalLayout_85.addWidget(self.channel_sel_34)
        self.verticalLayout.addWidget(self.widget_39)
        self.widget_40 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_40.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_40.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_40.setObjectName("widget_40")
        self.horizontalLayout_86 = QtWidgets.QHBoxLayout(self.widget_40)
        self.horizontalLayout_86.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_86.setSpacing(6)
        self.horizontalLayout_86.setObjectName("horizontalLayout_86")
        self.led_35 = QtWidgets.QLabel(self.widget_40)
        self.led_35.setMaximumSize(QtCore.QSize(16, 16))
        self.led_35.setText("")
        self.led_35.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_35.setObjectName("led_35")
        self.horizontalLayout_86.addWidget(self.led_35)
        self.channel_sel_35 = QtWidgets.QPushButton(self.widget_40)
        self.channel_sel_35.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_35.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_35.setFont(font)
        self.channel_sel_35.setObjectName("channel_sel_35")
        self.horizontalLayout_86.addWidget(self.channel_sel_35)
        self.verticalLayout.addWidget(self.widget_40)
        self.widget_41 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_41.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_41.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_41.setObjectName("widget_41")
        self.horizontalLayout_87 = QtWidgets.QHBoxLayout(self.widget_41)
        self.horizontalLayout_87.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_87.setSpacing(6)
        self.horizontalLayout_87.setObjectName("horizontalLayout_87")
        self.led_36 = QtWidgets.QLabel(self.widget_41)
        self.led_36.setMaximumSize(QtCore.QSize(16, 16))
        self.led_36.setText("")
        self.led_36.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_36.setObjectName("led_36")
        self.horizontalLayout_87.addWidget(self.led_36)
        self.channel_sel_36 = QtWidgets.QPushButton(self.widget_41)
        self.channel_sel_36.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_36.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_36.setFont(font)
        self.channel_sel_36.setObjectName("channel_sel_36")
        self.horizontalLayout_87.addWidget(self.channel_sel_36)
        self.verticalLayout.addWidget(self.widget_41)
        self.widget_42 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_42.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_42.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_42.setObjectName("widget_42")
        self.horizontalLayout_88 = QtWidgets.QHBoxLayout(self.widget_42)
        self.horizontalLayout_88.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_88.setSpacing(6)
        self.horizontalLayout_88.setObjectName("horizontalLayout_88")
        self.led_37 = QtWidgets.QLabel(self.widget_42)
        self.led_37.setMaximumSize(QtCore.QSize(16, 16))
        self.led_37.setText("")
        self.led_37.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_37.setObjectName("led_37")
        self.horizontalLayout_88.addWidget(self.led_37)
        self.channel_sel_37 = QtWidgets.QPushButton(self.widget_42)
        self.channel_sel_37.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_37.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_37.setFont(font)
        self.channel_sel_37.setObjectName("channel_sel_37")
        self.horizontalLayout_88.addWidget(self.channel_sel_37)
        self.verticalLayout.addWidget(self.widget_42)
        self.widget_43 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_43.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_43.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_43.setObjectName("widget_43")
        self.horizontalLayout_89 = QtWidgets.QHBoxLayout(self.widget_43)
        self.horizontalLayout_89.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_89.setSpacing(6)
        self.horizontalLayout_89.setObjectName("horizontalLayout_89")
        self.led_38 = QtWidgets.QLabel(self.widget_43)
        self.led_38.setMaximumSize(QtCore.QSize(16, 16))
        self.led_38.setText("")
        self.led_38.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_38.setObjectName("led_38")
        self.horizontalLayout_89.addWidget(self.led_38)
        self.channel_sel_38 = QtWidgets.QPushButton(self.widget_43)
        self.channel_sel_38.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_38.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_38.setFont(font)
        self.channel_sel_38.setObjectName("channel_sel_38")
        self.horizontalLayout_89.addWidget(self.channel_sel_38)
        self.verticalLayout.addWidget(self.widget_43)
        self.widget_44 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_44.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_44.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_44.setObjectName("widget_44")
        self.horizontalLayout_90 = QtWidgets.QHBoxLayout(self.widget_44)
        self.horizontalLayout_90.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_90.setSpacing(6)
        self.horizontalLayout_90.setObjectName("horizontalLayout_90")
        self.led_39 = QtWidgets.QLabel(self.widget_44)
        self.led_39.setMaximumSize(QtCore.QSize(16, 16))
        self.led_39.setText("")
        self.led_39.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_39.setObjectName("led_39")
        self.horizontalLayout_90.addWidget(self.led_39)
        self.channel_sel_39 = QtWidgets.QPushButton(self.widget_44)
        self.channel_sel_39.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_39.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_39.setFont(font)
        self.channel_sel_39.setObjectName("channel_sel_39")
        self.horizontalLayout_90.addWidget(self.channel_sel_39)
        self.verticalLayout.addWidget(self.widget_44)
        self.widget_45 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_45.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_45.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_45.setObjectName("widget_45")
        self.horizontalLayout_91 = QtWidgets.QHBoxLayout(self.widget_45)
        self.horizontalLayout_91.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_91.setSpacing(6)
        self.horizontalLayout_91.setObjectName("horizontalLayout_91")
        self.led_40 = QtWidgets.QLabel(self.widget_45)
        self.led_40.setMaximumSize(QtCore.QSize(16, 16))
        self.led_40.setText("")
        self.led_40.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_40.setObjectName("led_40")
        self.horizontalLayout_91.addWidget(self.led_40)
        self.channel_sel_40 = QtWidgets.QPushButton(self.widget_45)
        self.channel_sel_40.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_40.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_40.setFont(font)
        self.channel_sel_40.setObjectName("channel_sel_40")
        self.horizontalLayout_91.addWidget(self.channel_sel_40)
        self.verticalLayout.addWidget(self.widget_45)
        self.widget_46 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_46.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_46.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_46.setObjectName("widget_46")
        self.horizontalLayout_92 = QtWidgets.QHBoxLayout(self.widget_46)
        self.horizontalLayout_92.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_92.setSpacing(6)
        self.horizontalLayout_92.setObjectName("horizontalLayout_92")
        self.led_41 = QtWidgets.QLabel(self.widget_46)
        self.led_41.setMaximumSize(QtCore.QSize(16, 16))
        self.led_41.setText("")
        self.led_41.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_41.setObjectName("led_41")
        self.horizontalLayout_92.addWidget(self.led_41)
        self.channel_sel_41 = QtWidgets.QPushButton(self.widget_46)
        self.channel_sel_41.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_41.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_41.setFont(font)
        self.channel_sel_41.setObjectName("channel_sel_41")
        self.horizontalLayout_92.addWidget(self.channel_sel_41)
        self.verticalLayout.addWidget(self.widget_46)
        self.widget_47 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_47.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_47.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_47.setObjectName("widget_47")
        self.horizontalLayout_93 = QtWidgets.QHBoxLayout(self.widget_47)
        self.horizontalLayout_93.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_93.setSpacing(6)
        self.horizontalLayout_93.setObjectName("horizontalLayout_93")
        self.led_42 = QtWidgets.QLabel(self.widget_47)
        self.led_42.setMaximumSize(QtCore.QSize(16, 16))
        self.led_42.setText("")
        self.led_42.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_42.setObjectName("led_42")
        self.horizontalLayout_93.addWidget(self.led_42)
        self.channel_sel_42 = QtWidgets.QPushButton(self.widget_47)
        self.channel_sel_42.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_42.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_42.setFont(font)
        self.channel_sel_42.setObjectName("channel_sel_42")
        self.horizontalLayout_93.addWidget(self.channel_sel_42)
        self.verticalLayout.addWidget(self.widget_47)
        self.widget_48 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_48.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_48.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_48.setObjectName("widget_48")
        self.horizontalLayout_94 = QtWidgets.QHBoxLayout(self.widget_48)
        self.horizontalLayout_94.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_94.setSpacing(6)
        self.horizontalLayout_94.setObjectName("horizontalLayout_94")
        self.led_43 = QtWidgets.QLabel(self.widget_48)
        self.led_43.setMaximumSize(QtCore.QSize(16, 16))
        self.led_43.setText("")
        self.led_43.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_43.setObjectName("led_43")
        self.horizontalLayout_94.addWidget(self.led_43)
        self.channel_sel_43 = QtWidgets.QPushButton(self.widget_48)
        self.channel_sel_43.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_43.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_43.setFont(font)
        self.channel_sel_43.setObjectName("channel_sel_43")
        self.horizontalLayout_94.addWidget(self.channel_sel_43)
        self.verticalLayout.addWidget(self.widget_48)
        self.widget_49 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_49.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_49.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_49.setObjectName("widget_49")
        self.horizontalLayout_95 = QtWidgets.QHBoxLayout(self.widget_49)
        self.horizontalLayout_95.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_95.setSpacing(6)
        self.horizontalLayout_95.setObjectName("horizontalLayout_95")
        self.led_44 = QtWidgets.QLabel(self.widget_49)
        self.led_44.setMaximumSize(QtCore.QSize(16, 16))
        self.led_44.setText("")
        self.led_44.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_44.setObjectName("led_44")
        self.horizontalLayout_95.addWidget(self.led_44)
        self.channel_sel_44 = QtWidgets.QPushButton(self.widget_49)
        self.channel_sel_44.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_44.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_44.setFont(font)
        self.channel_sel_44.setObjectName("channel_sel_44")
        self.horizontalLayout_95.addWidget(self.channel_sel_44)
        self.verticalLayout.addWidget(self.widget_49)
        self.widget_50 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_50.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_50.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_50.setObjectName("widget_50")
        self.horizontalLayout_96 = QtWidgets.QHBoxLayout(self.widget_50)
        self.horizontalLayout_96.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_96.setSpacing(6)
        self.horizontalLayout_96.setObjectName("horizontalLayout_96")
        self.led_45 = QtWidgets.QLabel(self.widget_50)
        self.led_45.setMaximumSize(QtCore.QSize(16, 16))
        self.led_45.setText("")
        self.led_45.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_45.setObjectName("led_45")
        self.horizontalLayout_96.addWidget(self.led_45)
        self.channel_sel_45 = QtWidgets.QPushButton(self.widget_50)
        self.channel_sel_45.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_45.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_45.setFont(font)
        self.channel_sel_45.setObjectName("channel_sel_45")
        self.horizontalLayout_96.addWidget(self.channel_sel_45)
        self.verticalLayout.addWidget(self.widget_50)
        self.widget_51 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_51.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_51.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_51.setObjectName("widget_51")
        self.horizontalLayout_97 = QtWidgets.QHBoxLayout(self.widget_51)
        self.horizontalLayout_97.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_97.setSpacing(6)
        self.horizontalLayout_97.setObjectName("horizontalLayout_97")
        self.led_46 = QtWidgets.QLabel(self.widget_51)
        self.led_46.setMaximumSize(QtCore.QSize(16, 16))
        self.led_46.setText("")
        self.led_46.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_46.setObjectName("led_46")
        self.horizontalLayout_97.addWidget(self.led_46)
        self.channel_sel_46 = QtWidgets.QPushButton(self.widget_51)
        self.channel_sel_46.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_46.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_46.setFont(font)
        self.channel_sel_46.setObjectName("channel_sel_46")
        self.horizontalLayout_97.addWidget(self.channel_sel_46)
        self.verticalLayout.addWidget(self.widget_51)
        self.widget_52 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_52.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_52.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_52.setObjectName("widget_52")
        self.horizontalLayout_98 = QtWidgets.QHBoxLayout(self.widget_52)
        self.horizontalLayout_98.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_98.setSpacing(6)
        self.horizontalLayout_98.setObjectName("horizontalLayout_98")
        self.led_47 = QtWidgets.QLabel(self.widget_52)
        self.led_47.setMaximumSize(QtCore.QSize(16, 16))
        self.led_47.setText("")
        self.led_47.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_47.setObjectName("led_47")
        self.horizontalLayout_98.addWidget(self.led_47)
        self.channel_sel_47 = QtWidgets.QPushButton(self.widget_52)
        self.channel_sel_47.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_47.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_47.setFont(font)
        self.channel_sel_47.setObjectName("channel_sel_47")
        self.horizontalLayout_98.addWidget(self.channel_sel_47)
        self.verticalLayout.addWidget(self.widget_52)
        self.widget_53 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_53.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_53.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_53.setObjectName("widget_53")
        self.horizontalLayout_99 = QtWidgets.QHBoxLayout(self.widget_53)
        self.horizontalLayout_99.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_99.setSpacing(6)
        self.horizontalLayout_99.setObjectName("horizontalLayout_99")
        self.led_48 = QtWidgets.QLabel(self.widget_53)
        self.led_48.setMaximumSize(QtCore.QSize(16, 16))
        self.led_48.setText("")
        self.led_48.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_48.setObjectName("led_48")
        self.horizontalLayout_99.addWidget(self.led_48)
        self.channel_sel_48 = QtWidgets.QPushButton(self.widget_53)
        self.channel_sel_48.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_48.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_48.setFont(font)
        self.channel_sel_48.setObjectName("channel_sel_48")
        self.horizontalLayout_99.addWidget(self.channel_sel_48)
        self.verticalLayout.addWidget(self.widget_53)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)
        self.widget_2 = QtWidgets.QWidget(self.centralWidget)
        self.widget_2.setMinimumSize(QtCore.QSize(700, 0))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setMaximumSize(QtCore.QSize(700, 50))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.widget = QtWidgets.QWidget(self.widget_2)
        self.widget.setMaximumSize(QtCore.QSize(700, 242))
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 3)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_55 = QtWidgets.QWidget(self.widget)
        self.widget_55.setObjectName("widget_55")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_55)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.updateTo1 = QtWidgets.QPushButton(self.widget_55)
        self.updateTo1.setMaximumSize(QtCore.QSize(200, 27))
        self.updateTo1.setCheckable(True)
        self.updateTo1.setChecked(False)
        self.updateTo1.setObjectName("updateTo1")
        self.horizontalLayout_2.addWidget(self.updateTo1)
        self.memo1 = QtWidgets.QLineEdit(self.widget_55)
        self.memo1.setObjectName("memo1")
        self.horizontalLayout_2.addWidget(self.memo1)
        self.verticalLayout_4.addWidget(self.widget_55)
        self.display1 = PlotWidget(self.widget)
        self.display1.setObjectName("display1")
        self.verticalLayout_4.addWidget(self.display1)
        self.verticalLayout_3.addWidget(self.widget)
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setMaximumSize(QtCore.QSize(16777215, 242))
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_5.setContentsMargins(0, 3, 0, 0)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_56 = QtWidgets.QWidget(self.widget_4)
        self.widget_56.setObjectName("widget_56")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_56)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.updateTo2 = QtWidgets.QPushButton(self.widget_56)
        self.updateTo2.setMaximumSize(QtCore.QSize(200, 27))
        self.updateTo2.setCheckable(True)
        self.updateTo2.setChecked(False)
        self.updateTo2.setObjectName("updateTo2")
        self.horizontalLayout_3.addWidget(self.updateTo2)
        self.memo2 = QtWidgets.QLineEdit(self.widget_56)
        self.memo2.setObjectName("memo2")
        self.horizontalLayout_3.addWidget(self.memo2)
        self.verticalLayout_5.addWidget(self.widget_56)
        self.display2 = PlotWidget(self.widget_4)
        self.display2.setObjectName("display2")
        self.verticalLayout_5.addWidget(self.display2)
        self.verticalLayout_3.addWidget(self.widget_4)
        self.logWindow = QtWidgets.QPlainTextEdit(self.widget_2)
        self.logWindow.setMaximumSize(QtCore.QSize(700, 100))
        self.logWindow.setObjectName("logWindow")
        self.verticalLayout_3.addWidget(self.logWindow)
        self.horizontalLayout.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.centralWidget)
        self.widget_3.setMinimumSize(QtCore.QSize(350, 0))
        self.widget_3.setMaximumSize(QtCore.QSize(350, 800))
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_5 = QtWidgets.QWidget(self.widget_3)
        self.widget_5.setMaximumSize(QtCore.QSize(350, 100))
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_49 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_49.setContentsMargins(0, 11, 0, 11)
        self.horizontalLayout_49.setSpacing(6)
        self.horizontalLayout_49.setObjectName("horizontalLayout_49")
        self.fileName = QtWidgets.QLineEdit(self.widget_5)
        self.fileName.setMaximumSize(QtCore.QSize(200, 16777215))
        self.fileName.setObjectName("fileName")
        self.horizontalLayout_49.addWidget(self.fileName)
        self.findFile = QtWidgets.QPushButton(self.widget_5)
        self.findFile.setMaximumSize(QtCore.QSize(60, 16777215))
        self.findFile.setObjectName("findFile")
        self.horizontalLayout_49.addWidget(self.findFile)
        self.loadFile = QtWidgets.QPushButton(self.widget_5)
        self.loadFile.setMaximumSize(QtCore.QSize(60, 16777215))
        self.loadFile.setObjectName("loadFile")
        self.horizontalLayout_49.addWidget(self.loadFile)
        self.verticalLayout_2.addWidget(self.widget_5)
        self.widget_54 = QtWidgets.QWidget(self.widget_3)
        self.widget_54.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget_54.setObjectName("widget_54")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_54)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.savePath = QtWidgets.QLineEdit(self.widget_54)
        self.savePath.setMaximumSize(QtCore.QSize(200, 16777215))
        self.savePath.setObjectName("savePath")
        self.horizontalLayout_4.addWidget(self.savePath)
        self.saveButton = QtWidgets.QPushButton(self.widget_54)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout_4.addWidget(self.saveButton)
        self.verticalLayout_2.addWidget(self.widget_54)
        self.adcButton = QtWidgets.QPushButton(self.widget_3)
        self.adcButton.setObjectName("adcButton")
        self.verticalLayout_2.addWidget(self.adcButton)
        self.controlButton = QtWidgets.QPushButton(self.widget_3)
        self.controlButton.setObjectName("controlButton")
        self.verticalLayout_2.addWidget(self.controlButton)
        self.dacButton = QtWidgets.QPushButton(self.widget_3)
        self.dacButton.setObjectName("dacButton")
        self.verticalLayout_2.addWidget(self.dacButton)
        self.endButton = QtWidgets.QPushButton(self.widget_3)
        self.endButton.setObjectName("endButton")
        self.verticalLayout_2.addWidget(self.endButton)
        self.horizontalLayout.addWidget(self.widget_3)
        BioEECoinsMain.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(BioEECoinsMain)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1280, 25))
        self.menuBar.setObjectName("menuBar")
        BioEECoinsMain.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(BioEECoinsMain)
        self.statusBar.setObjectName("statusBar")
        BioEECoinsMain.setStatusBar(self.statusBar)

        self.retranslateUi(BioEECoinsMain)
        QtCore.QMetaObject.connectSlotsByName(BioEECoinsMain)

    def retranslateUi(self, BioEECoinsMain):
        _translate = QtCore.QCoreApplication.translate
        BioEECoinsMain.setWindowTitle(_translate("BioEECoinsMain", "BioEE Colony Inspector"))
        self.channel_sel_1.setText(_translate("BioEECoinsMain", "Channel   1"))
        self.channel_sel_2.setText(_translate("BioEECoinsMain", "Channel   2"))
        self.channel_sel_3.setText(_translate("BioEECoinsMain", "Channel   3"))
        self.channel_sel_4.setText(_translate("BioEECoinsMain", "Channel   4"))
        self.channel_sel_5.setText(_translate("BioEECoinsMain", "Channel   5"))
        self.channel_sel_6.setText(_translate("BioEECoinsMain", "Channel   6"))
        self.channel_sel_7.setText(_translate("BioEECoinsMain", "Channel   7"))
        self.channel_sel_8.setText(_translate("BioEECoinsMain", "Channel   8"))
        self.channel_sel_9.setText(_translate("BioEECoinsMain", "Channel   9"))
        self.channel_sel_10.setText(_translate("BioEECoinsMain", "Channel 10"))
        self.channel_sel_11.setText(_translate("BioEECoinsMain", "Channel 11"))
        self.channel_sel_12.setText(_translate("BioEECoinsMain", "Channel 12"))
        self.channel_sel_13.setText(_translate("BioEECoinsMain", "Channel 13"))
        self.channel_sel_14.setText(_translate("BioEECoinsMain", "Channel 14"))
        self.channel_sel_15.setText(_translate("BioEECoinsMain", "Channel 15"))
        self.channel_sel_16.setText(_translate("BioEECoinsMain", "Channel 16"))
        self.channel_sel_17.setText(_translate("BioEECoinsMain", "Channel 17"))
        self.channel_sel_18.setText(_translate("BioEECoinsMain", "Channel 18"))
        self.channel_sel_19.setText(_translate("BioEECoinsMain", "Channel 19"))
        self.channel_sel_20.setText(_translate("BioEECoinsMain", "Channel 20"))
        self.channel_sel_21.setText(_translate("BioEECoinsMain", "Channel 21"))
        self.channel_sel_22.setText(_translate("BioEECoinsMain", "Channel 22"))
        self.channel_sel_23.setText(_translate("BioEECoinsMain", "Channel 23"))
        self.channel_sel_24.setText(_translate("BioEECoinsMain", "Channel 24"))
        self.channel_sel_25.setText(_translate("BioEECoinsMain", "Channel 25"))
        self.channel_sel_26.setText(_translate("BioEECoinsMain", "Channel 26"))
        self.channel_sel_27.setText(_translate("BioEECoinsMain", "Channel 27"))
        self.channel_sel_28.setText(_translate("BioEECoinsMain", "Channel 28"))
        self.channel_sel_29.setText(_translate("BioEECoinsMain", "Channel 29"))
        self.channel_sel_30.setText(_translate("BioEECoinsMain", "Channel 30"))
        self.channel_sel_31.setText(_translate("BioEECoinsMain", "Channel 31"))
        self.channel_sel_32.setText(_translate("BioEECoinsMain", "Channel 32"))
        self.channel_sel_33.setText(_translate("BioEECoinsMain", "Channel 33"))
        self.channel_sel_34.setText(_translate("BioEECoinsMain", "Channel 34"))
        self.channel_sel_35.setText(_translate("BioEECoinsMain", "Channel 35"))
        self.channel_sel_36.setText(_translate("BioEECoinsMain", "Channel 36"))
        self.channel_sel_37.setText(_translate("BioEECoinsMain", "Channel 37"))
        self.channel_sel_38.setText(_translate("BioEECoinsMain", "Channel 38"))
        self.channel_sel_39.setText(_translate("BioEECoinsMain", "Test 1"))
        self.channel_sel_40.setText(_translate("BioEECoinsMain", "Test 2"))
        self.channel_sel_41.setText(_translate("BioEECoinsMain", "Test 3"))
        self.channel_sel_42.setText(_translate("BioEECoinsMain", "Test 4"))
        self.channel_sel_43.setText(_translate("BioEECoinsMain", "Test 5"))
        self.channel_sel_44.setText(_translate("BioEECoinsMain", "Test 6"))
        self.channel_sel_45.setText(_translate("BioEECoinsMain", "Test 7"))
        self.channel_sel_46.setText(_translate("BioEECoinsMain", "Test 8"))
        self.channel_sel_47.setText(_translate("BioEECoinsMain", "Extra 1"))
        self.channel_sel_48.setText(_translate("BioEECoinsMain", "Extra 2"))
        self.label.setText(_translate("BioEECoinsMain", "Electrochemical Camera Chip  "))
        self.updateTo1.setText(_translate("BioEECoinsMain", "Update to axis 1"))
        self.updateTo2.setText(_translate("BioEECoinsMain", "Update to axis 2"))
        self.findFile.setText(_translate("BioEECoinsMain", "Find..."))
        self.loadFile.setText(_translate("BioEECoinsMain", "Load"))
        self.saveButton.setText(_translate("BioEECoinsMain", "Save Data To ..."))
        self.adcButton.setText(_translate("BioEECoinsMain", "Send ADC Signal"))
        self.controlButton.setText(_translate("BioEECoinsMain", "Send Control Signal"))
        self.dacButton.setText(_translate("BioEECoinsMain", "Send DAC Signal"))
        self.endButton.setText(_translate("BioEECoinsMain", "End Task"))

from pyqtgraph import PlotWidget
