# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../GUI/BioEECoins/bioeecoinsmain.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BioEECoinsMain(object):
    def setupUi(self, BioEECoinsMain):
        BioEECoinsMain.setObjectName("BioEECoinsMain")
        BioEECoinsMain.resize(1280, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(BioEECoinsMain.sizePolicy().hasHeightForWidth())
        BioEECoinsMain.setSizePolicy(sizePolicy)
        BioEECoinsMain.setMinimumSize(QtCore.QSize(1280, 720))
        BioEECoinsMain.setMaximumSize(QtCore.QSize(1280, 720))
        self.centralWidget = QtWidgets.QWidget(BioEECoinsMain)
        self.centralWidget.setMaximumSize(QtCore.QSize(1280, 720))
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setContentsMargins(20, 20, 20, 20)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralWidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setEnabled(True)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 132, 1248))
        self.scrollAreaWidgetContents.setMaximumSize(QtCore.QSize(150, 2000))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_1.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_1.setSpacing(6)
        self.horizontalLayout_1.setObjectName("horizontalLayout_1")
        self.led_1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.led_1.setMaximumSize(QtCore.QSize(16, 16))
        self.led_1.setText("")
        self.led_1.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_1.setObjectName("led_1")
        self.horizontalLayout_1.addWidget(self.led_1)
        self.channel_sel_1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.channel_sel_1.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_1.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_1.setFont(font)
        self.channel_sel_1.setObjectName("channel_sel_1")
        self.horizontalLayout_1.addWidget(self.channel_sel_1)
        self.verticalLayout.addLayout(self.horizontalLayout_1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.led_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.led_2.setMaximumSize(QtCore.QSize(16, 16))
        self.led_2.setText("")
        self.led_2.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_2.setObjectName("led_2")
        self.horizontalLayout_2.addWidget(self.led_2)
        self.channel_sel_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.channel_sel_2.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_2.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_2.setFont(font)
        self.channel_sel_2.setObjectName("channel_sel_2")
        self.horizontalLayout_2.addWidget(self.channel_sel_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.led_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.led_3.setMaximumSize(QtCore.QSize(16, 16))
        self.led_3.setText("")
        self.led_3.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_3.setObjectName("led_3")
        self.horizontalLayout_3.addWidget(self.led_3)
        self.channel_sel_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.channel_sel_3.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_3.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_3.setFont(font)
        self.channel_sel_3.setObjectName("channel_sel_3")
        self.horizontalLayout_3.addWidget(self.channel_sel_3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.led_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.led_4.setMaximumSize(QtCore.QSize(16, 16))
        self.led_4.setText("")
        self.led_4.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_4.setObjectName("led_4")
        self.horizontalLayout_4.addWidget(self.led_4)
        self.channel_sel_4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.channel_sel_4.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_4.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_4.setFont(font)
        self.channel_sel_4.setObjectName("channel_sel_4")
        self.horizontalLayout_4.addWidget(self.channel_sel_4)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.led_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.led_5.setMaximumSize(QtCore.QSize(16, 16))
        self.led_5.setText("")
        self.led_5.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_5.setObjectName("led_5")
        self.horizontalLayout_5.addWidget(self.led_5)
        self.channel_sel_5 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.channel_sel_5.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_5.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_5.setFont(font)
        self.channel_sel_5.setObjectName("channel_sel_5")
        self.horizontalLayout_5.addWidget(self.channel_sel_5)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.led_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.led_6.setMaximumSize(QtCore.QSize(16, 16))
        self.led_6.setText("")
        self.led_6.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_6.setObjectName("led_6")
        self.horizontalLayout_6.addWidget(self.led_6)
        self.channel_sel_6 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.channel_sel_6.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_6.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_6.setFont(font)
        self.channel_sel_6.setObjectName("channel_sel_6")
        self.horizontalLayout_6.addWidget(self.channel_sel_6)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.led_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.led_7.setMaximumSize(QtCore.QSize(16, 16))
        self.led_7.setText("")
        self.led_7.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_7.setObjectName("led_7")
        self.horizontalLayout_7.addWidget(self.led_7)
        self.channel_sel_7 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.channel_sel_7.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_7.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_7.setFont(font)
        self.channel_sel_7.setObjectName("channel_sel_7")
        self.horizontalLayout_7.addWidget(self.channel_sel_7)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.led_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.led_8.setMaximumSize(QtCore.QSize(16, 16))
        self.led_8.setText("")
        self.led_8.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_8.setObjectName("led_8")
        self.horizontalLayout_8.addWidget(self.led_8)
        self.channel_sel_8 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.channel_sel_8.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_8.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_8.setFont(font)
        self.channel_sel_8.setObjectName("channel_sel_8")
        self.horizontalLayout_8.addWidget(self.channel_sel_8)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.led_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.led_9.setMaximumSize(QtCore.QSize(16, 16))
        self.led_9.setText("")
        self.led_9.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_9.setObjectName("led_9")
        self.horizontalLayout_9.addWidget(self.led_9)
        self.channel_sel_9 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.channel_sel_9.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_9.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_9.setFont(font)
        self.channel_sel_9.setObjectName("channel_sel_9")
        self.horizontalLayout_9.addWidget(self.channel_sel_9)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.led_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.led_10.setMaximumSize(QtCore.QSize(16, 16))
        self.led_10.setText("")
        self.led_10.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_10.setObjectName("led_10")
        self.horizontalLayout_10.addWidget(self.led_10)
        self.channel_sel_10 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.channel_sel_10.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_10.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_10.setFont(font)
        self.channel_sel_10.setObjectName("channel_sel_10")
        self.horizontalLayout_10.addWidget(self.channel_sel_10)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_11.setSpacing(6)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.led_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.led_11.setMaximumSize(QtCore.QSize(16, 16))
        self.led_11.setText("")
        self.led_11.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_11.setObjectName("led_11")
        self.horizontalLayout_11.addWidget(self.led_11)
        self.channel_sel_11 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.channel_sel_11.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_11.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_11.setFont(font)
        self.channel_sel_11.setObjectName("channel_sel_11")
        self.horizontalLayout_11.addWidget(self.channel_sel_11)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_12.setSpacing(6)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.led_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.led_12.setMaximumSize(QtCore.QSize(16, 16))
        self.led_12.setText("")
        self.led_12.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_12.setObjectName("led_12")
        self.horizontalLayout_12.addWidget(self.led_12)
        self.channel_sel_12 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.channel_sel_12.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_12.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_12.setFont(font)
        self.channel_sel_12.setObjectName("channel_sel_12")
        self.horizontalLayout_12.addWidget(self.channel_sel_12)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_13.setSpacing(6)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.led_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.led_13.setMaximumSize(QtCore.QSize(16, 16))
        self.led_13.setText("")
        self.led_13.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_13.setObjectName("led_13")
        self.horizontalLayout_13.addWidget(self.led_13)
        self.channel_sel_13 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.channel_sel_13.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_13.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_13.setFont(font)
        self.channel_sel_13.setObjectName("channel_sel_13")
        self.horizontalLayout_13.addWidget(self.channel_sel_13)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_14.setSpacing(6)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.led_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.led_14.setMaximumSize(QtCore.QSize(16, 16))
        self.led_14.setText("")
        self.led_14.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_14.setObjectName("led_14")
        self.horizontalLayout_14.addWidget(self.led_14)
        self.channel_sel_14 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.channel_sel_14.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_14.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_14.setFont(font)
        self.channel_sel_14.setObjectName("channel_sel_14")
        self.horizontalLayout_14.addWidget(self.channel_sel_14)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_15.setSpacing(6)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.led_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.led_15.setMaximumSize(QtCore.QSize(16, 16))
        self.led_15.setText("")
        self.led_15.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_15.setObjectName("led_15")
        self.horizontalLayout_15.addWidget(self.led_15)
        self.channel_sel_15 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.channel_sel_15.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_15.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_15.setFont(font)
        self.channel_sel_15.setObjectName("channel_sel_15")
        self.horizontalLayout_15.addWidget(self.channel_sel_15)
        self.verticalLayout.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_16.setSpacing(6)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.led_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.led_16.setMaximumSize(QtCore.QSize(16, 16))
        self.led_16.setText("")
        self.led_16.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_16.setObjectName("led_16")
        self.horizontalLayout_16.addWidget(self.led_16)
        self.channel_sel_16 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.channel_sel_16.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_16.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_16.setFont(font)
        self.channel_sel_16.setObjectName("channel_sel_16")
        self.horizontalLayout_16.addWidget(self.channel_sel_16)
        self.verticalLayout.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_17.setSpacing(6)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.led_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.led_17.setMaximumSize(QtCore.QSize(16, 16))
        self.led_17.setText("")
        self.led_17.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_17.setObjectName("led_17")
        self.horizontalLayout_17.addWidget(self.led_17)
        self.channel_sel_17 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.channel_sel_17.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_17.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_17.setFont(font)
        self.channel_sel_17.setObjectName("channel_sel_17")
        self.horizontalLayout_17.addWidget(self.channel_sel_17)
        self.verticalLayout.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_18.setSpacing(6)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.led_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.led_18.setMaximumSize(QtCore.QSize(16, 16))
        self.led_18.setText("")
        self.led_18.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_18.setObjectName("led_18")
        self.horizontalLayout_18.addWidget(self.led_18)
        self.channel_sel_18 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.channel_sel_18.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_18.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_18.setFont(font)
        self.channel_sel_18.setObjectName("channel_sel_18")
        self.horizontalLayout_18.addWidget(self.channel_sel_18)
        self.verticalLayout.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_19.setSpacing(6)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.led_19 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.led_19.setMaximumSize(QtCore.QSize(16, 16))
        self.led_19.setText("")
        self.led_19.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_19.setObjectName("led_19")
        self.horizontalLayout_19.addWidget(self.led_19)
        self.channel_sel_19 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.channel_sel_19.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_19.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_19.setFont(font)
        self.channel_sel_19.setObjectName("channel_sel_19")
        self.horizontalLayout_19.addWidget(self.channel_sel_19)
        self.verticalLayout.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_20.setSpacing(6)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.led_20 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.led_20.setMaximumSize(QtCore.QSize(16, 16))
        self.led_20.setText("")
        self.led_20.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_20.setObjectName("led_20")
        self.horizontalLayout_20.addWidget(self.led_20)
        self.channel_sel_20 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.channel_sel_20.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_20.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_20.setFont(font)
        self.channel_sel_20.setObjectName("channel_sel_20")
        self.horizontalLayout_20.addWidget(self.channel_sel_20)
        self.verticalLayout.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_21.setSpacing(6)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.led_21 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.led_21.setMaximumSize(QtCore.QSize(16, 16))
        self.led_21.setText("")
        self.led_21.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_21.setObjectName("led_21")
        self.horizontalLayout_21.addWidget(self.led_21)
        self.channel_sel_21 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.channel_sel_21.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_21.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_21.setFont(font)
        self.channel_sel_21.setObjectName("channel_sel_21")
        self.horizontalLayout_21.addWidget(self.channel_sel_21)
        self.verticalLayout.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_22.setSpacing(6)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.led_22 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.led_22.setMaximumSize(QtCore.QSize(16, 16))
        self.led_22.setText("")
        self.led_22.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_22.setObjectName("led_22")
        self.horizontalLayout_22.addWidget(self.led_22)
        self.channel_sel_22 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.channel_sel_22.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_22.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_22.setFont(font)
        self.channel_sel_22.setObjectName("channel_sel_22")
        self.horizontalLayout_22.addWidget(self.channel_sel_22)
        self.verticalLayout.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_23.setSpacing(6)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.led_23t = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.led_23t.setMaximumSize(QtCore.QSize(16, 16))
        self.led_23t.setText("")
        self.led_23t.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_23t.setObjectName("led_23t")
        self.horizontalLayout_23.addWidget(self.led_23t)
        self.channel_sel_23 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.channel_sel_23.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_23.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_23.setFont(font)
        self.channel_sel_23.setObjectName("channel_sel_23")
        self.horizontalLayout_23.addWidget(self.channel_sel_23)
        self.verticalLayout.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_24.setSpacing(6)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.led_24 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.led_24.setMaximumSize(QtCore.QSize(16, 16))
        self.led_24.setText("")
        self.led_24.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_24.setObjectName("led_24")
        self.horizontalLayout_24.addWidget(self.led_24)
        self.channel_sel_24 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.channel_sel_24.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_24.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_24.setFont(font)
        self.channel_sel_24.setObjectName("channel_sel_24")
        self.horizontalLayout_24.addWidget(self.channel_sel_24)
        self.verticalLayout.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_25.setSpacing(6)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.led_25 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.led_25.setMaximumSize(QtCore.QSize(16, 16))
        self.led_25.setText("")
        self.led_25.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_25.setObjectName("led_25")
        self.horizontalLayout_25.addWidget(self.led_25)
        self.channel_sel_25 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.channel_sel_25.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_25.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_25.setFont(font)
        self.channel_sel_25.setObjectName("channel_sel_25")
        self.horizontalLayout_25.addWidget(self.channel_sel_25)
        self.verticalLayout.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_26.setSpacing(6)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.led_26 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.led_26.setMaximumSize(QtCore.QSize(16, 16))
        self.led_26.setText("")
        self.led_26.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_26.setObjectName("led_26")
        self.horizontalLayout_26.addWidget(self.led_26)
        self.channel_sel_26 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.channel_sel_26.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_26.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_26.setFont(font)
        self.channel_sel_26.setObjectName("channel_sel_26")
        self.horizontalLayout_26.addWidget(self.channel_sel_26)
        self.verticalLayout.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_27.setSpacing(6)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.led_27 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.led_27.setMaximumSize(QtCore.QSize(16, 16))
        self.led_27.setText("")
        self.led_27.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_27.setObjectName("led_27")
        self.horizontalLayout_27.addWidget(self.led_27)
        self.channel_sel_27 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.channel_sel_27.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_27.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_27.setFont(font)
        self.channel_sel_27.setObjectName("channel_sel_27")
        self.horizontalLayout_27.addWidget(self.channel_sel_27)
        self.verticalLayout.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_28.setSpacing(6)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.led_28 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.led_28.setMaximumSize(QtCore.QSize(16, 16))
        self.led_28.setText("")
        self.led_28.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_28.setObjectName("led_28")
        self.horizontalLayout_28.addWidget(self.led_28)
        self.channel_sel_28 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.channel_sel_28.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_28.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_28.setFont(font)
        self.channel_sel_28.setObjectName("channel_sel_28")
        self.horizontalLayout_28.addWidget(self.channel_sel_28)
        self.verticalLayout.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_29.setSpacing(6)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.led_29 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.led_29.setMaximumSize(QtCore.QSize(16, 16))
        self.led_29.setText("")
        self.led_29.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_29.setObjectName("led_29")
        self.horizontalLayout_29.addWidget(self.led_29)
        self.channel_sel_29 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.channel_sel_29.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_29.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_29.setFont(font)
        self.channel_sel_29.setObjectName("channel_sel_29")
        self.horizontalLayout_29.addWidget(self.channel_sel_29)
        self.verticalLayout.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_30.setSpacing(6)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.led_30 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.led_30.setMaximumSize(QtCore.QSize(16, 16))
        self.led_30.setText("")
        self.led_30.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_30.setObjectName("led_30")
        self.horizontalLayout_30.addWidget(self.led_30)
        self.channel_sel_30 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.channel_sel_30.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_30.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_30.setFont(font)
        self.channel_sel_30.setObjectName("channel_sel_30")
        self.horizontalLayout_30.addWidget(self.channel_sel_30)
        self.verticalLayout.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_31.setSpacing(6)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.led_31 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.led_31.setMaximumSize(QtCore.QSize(16, 16))
        self.led_31.setText("")
        self.led_31.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_31.setObjectName("led_31")
        self.horizontalLayout_31.addWidget(self.led_31)
        self.channel_sel_31 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.channel_sel_31.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_31.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_31.setFont(font)
        self.channel_sel_31.setObjectName("channel_sel_31")
        self.horizontalLayout_31.addWidget(self.channel_sel_31)
        self.verticalLayout.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_32.setSpacing(6)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.led_32 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.led_32.setMaximumSize(QtCore.QSize(16, 16))
        self.led_32.setText("")
        self.led_32.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_32.setObjectName("led_32")
        self.horizontalLayout_32.addWidget(self.led_32)
        self.channel_sel_32 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.channel_sel_32.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_32.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_32.setFont(font)
        self.channel_sel_32.setObjectName("channel_sel_32")
        self.horizontalLayout_32.addWidget(self.channel_sel_32)
        self.verticalLayout.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_33.setSpacing(6)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.led_33 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.led_33.setMaximumSize(QtCore.QSize(16, 16))
        self.led_33.setText("")
        self.led_33.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_33.setObjectName("led_33")
        self.horizontalLayout_33.addWidget(self.led_33)
        self.channel_sel_33 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.channel_sel_33.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_33.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_33.setFont(font)
        self.channel_sel_33.setObjectName("channel_sel_33")
        self.horizontalLayout_33.addWidget(self.channel_sel_33)
        self.verticalLayout.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_34.setSpacing(6)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.led_34 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.led_34.setMaximumSize(QtCore.QSize(16, 16))
        self.led_34.setText("")
        self.led_34.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_34.setObjectName("led_34")
        self.horizontalLayout_34.addWidget(self.led_34)
        self.channel_sel_34 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.channel_sel_34.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_34.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_34.setFont(font)
        self.channel_sel_34.setObjectName("channel_sel_34")
        self.horizontalLayout_34.addWidget(self.channel_sel_34)
        self.verticalLayout.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_35.setSpacing(6)
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.led_35 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.led_35.setMaximumSize(QtCore.QSize(16, 16))
        self.led_35.setText("")
        self.led_35.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_35.setObjectName("led_35")
        self.horizontalLayout_35.addWidget(self.led_35)
        self.channel_sel_35 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.channel_sel_35.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_35.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_35.setFont(font)
        self.channel_sel_35.setObjectName("channel_sel_35")
        self.horizontalLayout_35.addWidget(self.channel_sel_35)
        self.verticalLayout.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_36.setSpacing(6)
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.led_36 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.led_36.setMaximumSize(QtCore.QSize(16, 16))
        self.led_36.setText("")
        self.led_36.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_36.setObjectName("led_36")
        self.horizontalLayout_36.addWidget(self.led_36)
        self.channel_sel_36 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.channel_sel_36.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_36.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_36.setFont(font)
        self.channel_sel_36.setObjectName("channel_sel_36")
        self.horizontalLayout_36.addWidget(self.channel_sel_36)
        self.verticalLayout.addLayout(self.horizontalLayout_36)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_37.setSpacing(6)
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.led_37 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.led_37.setMaximumSize(QtCore.QSize(16, 16))
        self.led_37.setText("")
        self.led_37.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_37.setObjectName("led_37")
        self.horizontalLayout_37.addWidget(self.led_37)
        self.channel_sel_37 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.channel_sel_37.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_37.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_37.setFont(font)
        self.channel_sel_37.setObjectName("channel_sel_37")
        self.horizontalLayout_37.addWidget(self.channel_sel_37)
        self.verticalLayout.addLayout(self.horizontalLayout_37)
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_38.setSpacing(6)
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.led_38 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.led_38.setMaximumSize(QtCore.QSize(16, 16))
        self.led_38.setText("")
        self.led_38.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_38.setObjectName("led_38")
        self.horizontalLayout_38.addWidget(self.led_38)
        self.channel_sel_38 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.channel_sel_38.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_38.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_38.setFont(font)
        self.channel_sel_38.setObjectName("channel_sel_38")
        self.horizontalLayout_38.addWidget(self.channel_sel_38)
        self.verticalLayout.addLayout(self.horizontalLayout_38)
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_39.setSpacing(6)
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.led_39 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.led_39.setMaximumSize(QtCore.QSize(16, 16))
        self.led_39.setText("")
        self.led_39.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_39.setObjectName("led_39")
        self.horizontalLayout_39.addWidget(self.led_39)
        self.channel_sel_39 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.channel_sel_39.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_39.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_39.setFont(font)
        self.channel_sel_39.setObjectName("channel_sel_39")
        self.horizontalLayout_39.addWidget(self.channel_sel_39)
        self.verticalLayout.addLayout(self.horizontalLayout_39)
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_40.setSpacing(6)
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.led_40 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.led_40.setMaximumSize(QtCore.QSize(16, 16))
        self.led_40.setText("")
        self.led_40.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_40.setObjectName("led_40")
        self.horizontalLayout_40.addWidget(self.led_40)
        self.channel_sel_40 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.channel_sel_40.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_40.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_40.setFont(font)
        self.channel_sel_40.setObjectName("channel_sel_40")
        self.horizontalLayout_40.addWidget(self.channel_sel_40)
        self.verticalLayout.addLayout(self.horizontalLayout_40)
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_41.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_41.setSpacing(6)
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.led_41 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.led_41.setMaximumSize(QtCore.QSize(16, 16))
        self.led_41.setText("")
        self.led_41.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_41.setObjectName("led_41")
        self.horizontalLayout_41.addWidget(self.led_41)
        self.channel_sel_41 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.channel_sel_41.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_41.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_41.setFont(font)
        self.channel_sel_41.setObjectName("channel_sel_41")
        self.horizontalLayout_41.addWidget(self.channel_sel_41)
        self.verticalLayout.addLayout(self.horizontalLayout_41)
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_42.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_42.setSpacing(6)
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.led_42 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.led_42.setMaximumSize(QtCore.QSize(16, 16))
        self.led_42.setText("")
        self.led_42.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_42.setObjectName("led_42")
        self.horizontalLayout_42.addWidget(self.led_42)
        self.channel_sel_42 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.channel_sel_42.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_42.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_42.setFont(font)
        self.channel_sel_42.setObjectName("channel_sel_42")
        self.horizontalLayout_42.addWidget(self.channel_sel_42)
        self.verticalLayout.addLayout(self.horizontalLayout_42)
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_43.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_43.setSpacing(6)
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.led_43 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.led_43.setMaximumSize(QtCore.QSize(16, 16))
        self.led_43.setText("")
        self.led_43.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_43.setObjectName("led_43")
        self.horizontalLayout_43.addWidget(self.led_43)
        self.channel_sel_43 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.channel_sel_43.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_43.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_43.setFont(font)
        self.channel_sel_43.setObjectName("channel_sel_43")
        self.horizontalLayout_43.addWidget(self.channel_sel_43)
        self.verticalLayout.addLayout(self.horizontalLayout_43)
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_44.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_44.setSpacing(6)
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.led_44 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.led_44.setMaximumSize(QtCore.QSize(16, 16))
        self.led_44.setText("")
        self.led_44.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_44.setObjectName("led_44")
        self.horizontalLayout_44.addWidget(self.led_44)
        self.channel_sel_44 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.channel_sel_44.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_44.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_44.setFont(font)
        self.channel_sel_44.setObjectName("channel_sel_44")
        self.horizontalLayout_44.addWidget(self.channel_sel_44)
        self.verticalLayout.addLayout(self.horizontalLayout_44)
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_45.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_45.setSpacing(6)
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.led_45 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.led_45.setMaximumSize(QtCore.QSize(16, 16))
        self.led_45.setText("")
        self.led_45.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_45.setObjectName("led_45")
        self.horizontalLayout_45.addWidget(self.led_45)
        self.channel_sel_45 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.channel_sel_45.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_45.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_45.setFont(font)
        self.channel_sel_45.setObjectName("channel_sel_45")
        self.horizontalLayout_45.addWidget(self.channel_sel_45)
        self.verticalLayout.addLayout(self.horizontalLayout_45)
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_46.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_46.setSpacing(6)
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.led_46t = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.led_46t.setMaximumSize(QtCore.QSize(16, 16))
        self.led_46t.setText("")
        self.led_46t.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_46t.setObjectName("led_46t")
        self.horizontalLayout_46.addWidget(self.led_46t)
        self.channel_sel_46 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.channel_sel_46.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_46.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_46.setFont(font)
        self.channel_sel_46.setObjectName("channel_sel_46")
        self.horizontalLayout_46.addWidget(self.channel_sel_46)
        self.verticalLayout.addLayout(self.horizontalLayout_46)
        self.horizontalLayout_47 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_47.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_47.setSpacing(6)
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.led_47 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.led_47.setMaximumSize(QtCore.QSize(16, 16))
        self.led_47.setText("")
        self.led_47.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_47.setObjectName("led_47")
        self.horizontalLayout_47.addWidget(self.led_47)
        self.channel_sel_47 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.channel_sel_47.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_47.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_47.setFont(font)
        self.channel_sel_47.setObjectName("channel_sel_47")
        self.horizontalLayout_47.addWidget(self.channel_sel_47)
        self.verticalLayout.addLayout(self.horizontalLayout_47)
        self.horizontalLayout_48 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_48.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_48.setSpacing(6)
        self.horizontalLayout_48.setObjectName("horizontalLayout_48")
        self.led_48 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.led_48.setMaximumSize(QtCore.QSize(16, 16))
        self.led_48.setText("")
        self.led_48.setPixmap(QtGui.QPixmap("led/led_gray.png"))
        self.led_48.setObjectName("led_48")
        self.horizontalLayout_48.addWidget(self.led_48)
        self.channel_sel_48 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.channel_sel_48.setMinimumSize(QtCore.QSize(80, 0))
        self.channel_sel_48.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.channel_sel_48.setFont(font)
        self.channel_sel_48.setObjectName("channel_sel_48")
        self.horizontalLayout_48.addWidget(self.channel_sel_48)
        self.verticalLayout.addLayout(self.horizontalLayout_48)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)
        self.widget_2 = QtWidgets.QWidget(self.centralWidget)
        self.widget_2.setMinimumSize(QtCore.QSize(700, 0))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setMaximumSize(QtCore.QSize(700, 50))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.widget = QtWidgets.QWidget(self.widget_2)
        self.widget.setMaximumSize(QtCore.QSize(700, 242))
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.updateTo1 = QtWidgets.QPushButton(self.widget)
        self.updateTo1.setMaximumSize(QtCore.QSize(200, 27))
        self.updateTo1.setCheckable(True)
        self.updateTo1.setChecked(False)
        self.updateTo1.setObjectName("updateTo1")
        self.verticalLayout_4.addWidget(self.updateTo1)
        self.display1 = PlotWidget(self.widget)
        self.display1.setObjectName("display1")
        self.verticalLayout_4.addWidget(self.display1)
        self.verticalLayout_3.addWidget(self.widget)
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setMaximumSize(QtCore.QSize(16777215, 242))
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.u = QtWidgets.QPushButton(self.widget_4)
        self.u.setMaximumSize(QtCore.QSize(200, 27))
        self.u.setCheckable(True)
        self.u.setChecked(False)
        self.u.setObjectName("u")
        self.verticalLayout_5.addWidget(self.u)
        self.display2 = PlotWidget(self.widget_4)
        self.display2.setObjectName("display2")
        self.verticalLayout_5.addWidget(self.display2)
        self.verticalLayout_3.addWidget(self.widget_4)
        self.logWindow = QtWidgets.QPlainTextEdit(self.widget_2)
        self.logWindow.setMaximumSize(QtCore.QSize(700, 100))
        self.logWindow.setObjectName("logWindow")
        self.verticalLayout_3.addWidget(self.logWindow)
        self.horizontalLayout.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.centralWidget)
        self.widget_3.setMinimumSize(QtCore.QSize(350, 0))
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.fileName = QtWidgets.QLineEdit(self.widget_3)
        self.fileName.setObjectName("fileName")
        self.verticalLayout_2.addWidget(self.fileName)
        self.adcButton = QtWidgets.QPushButton(self.widget_3)
        self.adcButton.setObjectName("adcButton")
        self.verticalLayout_2.addWidget(self.adcButton)
        self.controlButton = QtWidgets.QPushButton(self.widget_3)
        self.controlButton.setObjectName("controlButton")
        self.verticalLayout_2.addWidget(self.controlButton)
        self.dacButton = QtWidgets.QPushButton(self.widget_3)
        self.dacButton.setObjectName("dacButton")
        self.verticalLayout_2.addWidget(self.dacButton)
        self.horizontalLayout.addWidget(self.widget_3)
        BioEECoinsMain.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(BioEECoinsMain)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1280, 25))
        self.menuBar.setObjectName("menuBar")
        self.menuBioEE_CoIns = QtWidgets.QMenu(self.menuBar)
        self.menuBioEE_CoIns.setObjectName("menuBioEE_CoIns")
        BioEECoinsMain.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(BioEECoinsMain)
        self.statusBar.setObjectName("statusBar")
        BioEECoinsMain.setStatusBar(self.statusBar)
        self.menuBar.addAction(self.menuBioEE_CoIns.menuAction())

        self.retranslateUi(BioEECoinsMain)
        QtCore.QMetaObject.connectSlotsByName(BioEECoinsMain)

    def retranslateUi(self, BioEECoinsMain):
        _translate = QtCore.QCoreApplication.translate
        BioEECoinsMain.setWindowTitle(_translate("BioEECoinsMain", "BioEE Colony Inspector"))
        self.channel_sel_1.setText(_translate("BioEECoinsMain", "Channel 1"))
        self.channel_sel_2.setText(_translate("BioEECoinsMain", "Channel 2"))
        self.channel_sel_3.setText(_translate("BioEECoinsMain", "Channel 3"))
        self.channel_sel_4.setText(_translate("BioEECoinsMain", "Channel 4"))
        self.channel_sel_5.setText(_translate("BioEECoinsMain", "Channel 5"))
        self.channel_sel_6.setText(_translate("BioEECoinsMain", "Channel 6"))
        self.channel_sel_7.setText(_translate("BioEECoinsMain", "Channel 7"))
        self.channel_sel_8.setText(_translate("BioEECoinsMain", "Channel 8"))
        self.channel_sel_9.setText(_translate("BioEECoinsMain", "Channel 9"))
        self.channel_sel_10.setText(_translate("BioEECoinsMain", "Channel 10"))
        self.channel_sel_11.setText(_translate("BioEECoinsMain", "Channel 11"))
        self.channel_sel_12.setText(_translate("BioEECoinsMain", "Channel 12"))
        self.channel_sel_13.setText(_translate("BioEECoinsMain", "Channel 13"))
        self.channel_sel_14.setText(_translate("BioEECoinsMain", "Channel 14"))
        self.channel_sel_15.setText(_translate("BioEECoinsMain", "Channel 15"))
        self.channel_sel_16.setText(_translate("BioEECoinsMain", "Channel 16"))
        self.channel_sel_17.setText(_translate("BioEECoinsMain", "Channel 17"))
        self.channel_sel_18.setText(_translate("BioEECoinsMain", "Channel 18"))
        self.channel_sel_19.setText(_translate("BioEECoinsMain", "Channel 19"))
        self.channel_sel_20.setText(_translate("BioEECoinsMain", "Channel 20"))
        self.channel_sel_21.setText(_translate("BioEECoinsMain", "Channel 21"))
        self.channel_sel_22.setText(_translate("BioEECoinsMain", "Channel 22"))
        self.channel_sel_23.setText(_translate("BioEECoinsMain", "Channel 23"))
        self.channel_sel_24.setText(_translate("BioEECoinsMain", "Channel 24"))
        self.channel_sel_25.setText(_translate("BioEECoinsMain", "Channel 25"))
        self.channel_sel_26.setText(_translate("BioEECoinsMain", "Channel 26"))
        self.channel_sel_27.setText(_translate("BioEECoinsMain", "Channel 27"))
        self.channel_sel_28.setText(_translate("BioEECoinsMain", "Channel 28"))
        self.channel_sel_29.setText(_translate("BioEECoinsMain", "Channel 29"))
        self.channel_sel_30.setText(_translate("BioEECoinsMain", "Channel 30"))
        self.channel_sel_31.setText(_translate("BioEECoinsMain", "Channel 31"))
        self.channel_sel_32.setText(_translate("BioEECoinsMain", "Channel 32"))
        self.channel_sel_33.setText(_translate("BioEECoinsMain", "Channel 33"))
        self.channel_sel_34.setText(_translate("BioEECoinsMain", "Channel 34"))
        self.channel_sel_35.setText(_translate("BioEECoinsMain", "Channel 35"))
        self.channel_sel_36.setText(_translate("BioEECoinsMain", "Channel 36"))
        self.channel_sel_37.setText(_translate("BioEECoinsMain", "Channel 37"))
        self.channel_sel_38.setText(_translate("BioEECoinsMain", "Channel 38"))
        self.channel_sel_39.setText(_translate("BioEECoinsMain", "Test 1"))
        self.channel_sel_40.setText(_translate("BioEECoinsMain", "Test 2"))
        self.channel_sel_41.setText(_translate("BioEECoinsMain", "Test 3"))
        self.channel_sel_42.setText(_translate("BioEECoinsMain", "Test 4"))
        self.channel_sel_43.setText(_translate("BioEECoinsMain", "Test 5"))
        self.channel_sel_44.setText(_translate("BioEECoinsMain", "Test 6"))
        self.channel_sel_45.setText(_translate("BioEECoinsMain", "Test 7"))
        self.channel_sel_46.setText(_translate("BioEECoinsMain", "Test 8"))
        self.channel_sel_47.setText(_translate("BioEECoinsMain", "Extra 1"))
        self.channel_sel_48.setText(_translate("BioEECoinsMain", "Extra 2"))
        self.label.setText(_translate("BioEECoinsMain", "Electrochemical Camera Chip  "))
        self.updateTo1.setText(_translate("BioEECoinsMain", "Update to axis 1"))
        self.u.setText(_translate("BioEECoinsMain", "Update to axis 2"))
        self.adcButton.setText(_translate("BioEECoinsMain", "Send ADC signal"))
        self.controlButton.setText(_translate("BioEECoinsMain", "Send Control Signal"))
        self.dacButton.setText(_translate("BioEECoinsMain", "Send DAC signal"))
        self.menuBioEE_CoIns.setTitle(_translate("BioEECoinsMain", "File"))

from pyqtgraph import PlotWidget
